### ISSUE TITLE
Each Facet/@type require to have IRIs (`@id`s)

### ISSUE THREAD

**Issue by fabrizio-turchi** [casework/CASE-Mapping-Python#2]
Each Facet does get its own different @id, with its own distinct UUIDv4 (https://github.com/ucoProject/UCO/issues/430). 
Example:
``` json
{
            "@id": "kb:5340d5ad-0fe1-463c-a461-f211e64edfd4",
            "@type": "uco-observable:ObservableObject",
            "uco-core:hasFacet": [
                {
                    "@id": "kb:1723ed9c-2d8e-415c-8cf6-31599c49df79",
                    "@type": "uco-observable:ApplicationFacet",
                    "uco-observable:applicationIdentifier": "com.whatsapp",
                    "uco-observable:version": "1.23.45"
                }
            ]
     }
```

**Comment by kchason** [comment]
Is this not completed in https://github.com/casework/CASE-Mapping-Python/blob/main/case_builder/base.py#L21?

It looks like when generating an example graph with `python3 example.py` it's properly setting `@id` properties for `*Facet` and it's validating against `case_validate` in https://github.com/kchason/CASE-Mapping-Python/actions/runs/6394211301

**Comment by ajnelson-nist** [comment]
@kchason : Good catch!  It's this line (revising link to permalink):

https://github.com/casework/CASE-Mapping-Python/blob/138ff12/case_builder/base.py#L23

Yes, this Issue seems addressed already.
