### ISSUE TITLE
xsd:nonNegativeInteger to be supported

### ISSUE THREAD

**Issue by ajnelson-nist** [casework/CASE-Mapping-Python#37]
There are several properties across the `core`, `action`, and `observable` namespaces that use `xsd:nonNegativeInteger`.  One happens to be referenced in `example.py`.  The other properties will need a general library function to support their usage.

**Comment by ajnelson-nist** [comment]
@fabrizio-turchi : I believe [`UcoThing._nonegative_int_vars()`](https://github.com/casework/CASE-Mapping-Python/blob/4a507867a724c7b96242da0ca5a9879bc22a06cf/case_mapping/base.py#L133-L138) is the function needed by this issue.  If you've checked whether it is called everywhere it should be, please feel free to close this issue as addressed.

**Comment by fabrizio-turchi** [comment]
Yes I'll close it, it's called for the following properties:
entity.py
    "drafting:reactionsCount": reactions_count,
    "drafting:sharesCount": shares_count,
    "drafting:commentsCount": comments_count
action.py
"uco-action:actionCount": action_count
